baseurl: ""
url: "https://friedenauplastikfrei.github.io"

title: "Friedenau Plastikfrei"
description: "Webauftritt der Nachbarschaftsinitiative Friedenau Plastikfrei"
avatar: "assets/img/logo.svg"
favicon: "assets/favicon.ico"

header_text: '<img alt="logo" src="/assets/img/logo.svg">'
header_feature_image: "assets/img/garbage.jpg"
footer_text: '<a href="/impressum">Impressum</a>, <a href="/datenschutz">Datenschutzerklärung</a>, <a href="/attribution">Attribution</a>'

excerpt: true
post_navigation: true

theme: type-on-strap
remote_theme: sylhare/Type-on-Strap
